"""Rule helper definitions used by the ASC Lite MVP logic.

The helpers in this module are intentionally small and dependency-free so they
can be tested in isolation and combined by the future rule engine.
"""

from __future__ import annotations

WINDOW_PROTECTION_RULE_ID = "R-WIN-001"
WINDOW_RESUME_RULE_ID = "R-WIN-002"
PARTY_SUPPRESS_RULE_ID = "R-PARTY-001"
PARTY_RESUME_RULE_ID = "R-PARTY-002"
PRESENCE_AWAY_CLOSE_RULE_ID = "R-PRES-001"
PRESENCE_AWAY_FORCED_OPEN_RULE_ID = "R-PRES-002"
PRESENCE_HOME_OPEN_RULE_ID = "R-PRES-003"
ASTRO_EVENING_CLOSE_RULE_ID = "R-ASTRO-001"
ASTRO_MORNING_OPEN_RULE_ID = "R-ASTRO-002"
LUX_SHADING_IN_RULE_ID = "R-LUX-001"
LUX_SHADING_OUT_RULE_ID = "R-LUX-002"

__all__ = [
    "ASTRO_EVENING_CLOSE_RULE_ID",
    "ASTRO_MORNING_OPEN_RULE_ID",
    "LUX_SHADING_IN_RULE_ID",
    "LUX_SHADING_OUT_RULE_ID",
    "PARTY_RESUME_RULE_ID",
    "PARTY_SUPPRESS_RULE_ID",
    "PRESENCE_AWAY_CLOSE_RULE_ID",
    "PRESENCE_AWAY_FORCED_OPEN_RULE_ID",
    "PRESENCE_HOME_OPEN_RULE_ID",
    "WINDOW_PROTECTION_RULE_ID",
    "WINDOW_RESUME_RULE_ID",
]
